project:
  type: website

website:
  title: "reproduce.work"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: floating

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


resource-files:
  - files
  - files/scripts/install.sh
