project:
  type: website

website:
  title: "reproduce.work"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - sidebar:docs
      - about.qmd
      

  sidebar:
    - id: docs
      title: "Documentation"
      style: "floating"
      background: light
      contents:
      - section: Getting Started
        contents:
          - href: docs/getting-started.qmd#installation
            text: Installation
          - href: docs/getting-started.qmd#basic-commands
            text: Basic Commands
      - section: Scientific computing environments
        contents: 
          - href: docs/jupyter.qmd
            text: "`jupyter`"
      - section: Document environments
        contents: 
          - href: docs/markdown-latex.qmd
            text: "`markdown-latex`"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

resource-files:
  - files
