---
title: "About"
sidebar: false
---

## Creator

The reproduce.work framework is being developed by [Alex P. Miller](https://alexmiller.phd), Assistant Professor of Marketing at the USC Marshall School of Business. It is currently a proof-of-concept prototype and is under active development. If you are interested in using the framework, contributing, or discussing its future, [please reach out directly](mailto:alex.miller@marshall.usc.edu).


## Why containerization?
    
**And how is this different from existing efforts in open science?**

Reproducibility is core to the philosophy and practice of science. However, as the credibility revolution in recent years has shown, the practice of science has fallen woefully short of meeting even basic standards toward true and widespread reproducibility. The recent interest in *open* science has been a positive step toward improving the reproducibility of scientific research, but the open science movement has largely focused on the *transparency* of scientific research, rather than explicilty facilitating its *reproducibility*. Many of the tools and practices of open science --- open data, open code, pre-registration, etc. --- are important steps toward reproducibility, but they are not sufficient, as they require authors to provide detailed documentation and instructions to ensure that others can independently replicate their work. This work is often left undone and, even when it is, writing adequate documentation and troubleshooting cross-platform execution errors can be a time-consuming and error-prone process.

By packaging the entire scientific environment --- software, dependencies, data, and manuscripts --- into containers, scientists can ensure that their experiments and analyses can be replicated exactly, irrespective of changes in underlying technology or platforms. This approach enhances the reliability of scientific findings and facilitates collaboration --- both within research teams but also across the broader scientific community by allowing anyone, anywhere, anytime to build upon the work of others.


